### ISSUE TITLE
Set cookies or any other http header

### ISSUE THREAD

**Issue by ArmstrongCN** [ui4j/ui4j#11]
Does ui4j provide ways to set request headers?

**Comment by ui4j** [comment]
Hi, this feature is available with version 1.2.0. Please check the unit tests for sample usage.
https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/CookieTest.java
https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/HeaderTest.java
