### ISSUE TITLE
Add support for cookies

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#26]
It would be nice to be able to set cookies like the user agent as a per browser instance.

**Comment by hstaudacher** [comment]
Any opinion?

**Comment by ui4j** [comment]
Sorry for the late response.

As far as i know WebView doesnt let to intercept http connections.
But i try to hack [1] undocumented api to intercept http requests. Initial implementation seems work for simple use cases. You could checkout master branch and execute the unit tests. Let me know if api or implementation isn't sufficient for your requirements.

Unit test:
https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/CookieTest.java
https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/HeaderTest.java

[1] https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/main/java/com/ui4j/webkit/WebKitBrowser.java#L399

**Comment by hstaudacher** [comment]
Hi, thanks for adding this feature. It looks like it is sufficient. But one thing is bothering me. 

Am I right that I have to set the cookie in the beforeLoad method? If yes its kind of weird that this method returns a request. As in your unit test it returns null. What does null mean at this point. Wouldn't it be better to pass the request object created with the already configured url into this method? This would also make the api more symetric because the response is also passed as a parameter.

**Comment by hstaudacher** [comment]
Oh I just noticed that its not possible to set cookies with the current Request implementation.  So, I have to revert my earlier statement ;). Current state is not sufficient.

**Comment by ui4j** [comment]
> This would also make the api more symetric because the response is also passed as a parameter.

I changed the return type to void and beforeLoad takes Request argument and afterLoad takes Response argument.

You can use new Request.setCookies(HttpCookie) to manage cookies. Please review updated unit tests for the sample usage: https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/CookieTest.java

**Comment by hstaudacher** [comment]
Looks good. Just one thing. What is the reason that the before and after methods take the uri as string? Can't they be obtained from request and response?

Sorry to be so picky. Just want to make sure the Api is good ;).

**Comment by ui4j** [comment]
I agree with you, its better to access url from Request and Response class.
If the latest implementation & api satisfy your requirements, i am going to relase the new version.

**Comment by hstaudacher** [comment]
+1

**Comment by ui4j** [comment]
Version 1.2.0 is ready to use with Interceptor feature.
