### ISSUE TITLE
Remove waitUntilDocReady Method

### ISSUE THREAD

**Issue by ui4j** [ui4j/ui4j#27]
Its unnecessary to call all methods with wait prefix.
Ui4j must suspend the call and waits until page loading is done.

instead of:
```java
document.query("#mylink");
document.waitUntilDocReady();
System.out.println(document.getTitle());
```
This way is better:
```java
document.query("#mylink");
// <- Suspend the thread until page loads
System.out.println(document.getTitle());
```

**Comment by hstaudacher** [comment]
Hi, I saw you have increased the version to 1.3 with this change. Just one side node. This is a breaking change. Increasing only the minor version does not reflect that there are API changes. From a semantic version point of view this change should increase the version to 2.0 to indicate the breaking API.

**Comment by ui4j** [comment]
Ok, it's reasonable to change the version 2.0
