### ISSUE TITLE
setInnerHTML on Element does not work

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#33]
as the description says. Calling this method does not have any effect.

**Comment by ui4j** [comment]
Hi,

I am unable to reproduce the bug.
[t14_innerHTML()](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/test/java/com/ui4j/test/ElementTest.java#L197) pass the test.

Here is code snippet that works for me:

```java
package com.ui4j.test;

import com.ui4j.api.browser.BrowserEngine;
import com.ui4j.api.browser.BrowserFactory;
import com.ui4j.api.browser.Page;
import com.ui4j.api.dom.Element;

public class Main {

	public static void main(String[] args) {
		BrowserEngine webkit = BrowserFactory.getWebKit();
		Page page = webkit.navigate("about:blank");
		page.show();
		Element div = page.getDocument().createElement("div");
		div.setInnerHTML("<span style=\"color: red\">test</span>");
		page.getDocument().getBody().append(div);
	}
}
```

Please submit your test case if possible.

**Comment by hstaudacher** [comment]
This is the html file"

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id="with-inner"><span id="inner"></span></div>
  </body>
</html>
```

this is the java code:

```
Element withInner = element.getDocument().query( "#with-inner" );
withInner.setInnerHTML( "<span id=\"blub\"></span>" );

String innerHTML = withInner.getInnerHTML();

assertThat( innerHTML ).isEqualTo( "<span id=\"blub\"></span>" );
```

**Comment by ui4j** [comment]
I am still couldnt reproduce the bug. I am using `assertEquals` method instead `of assertThat`. The problem might be releated with hamcrest matcher api. The latest unit test pass for the Windows 8.1 and Ubuntu enviornments.

**Comment by hstaudacher** [comment]
Damn it. My fault, sorry. I created an abstraction for ui4j and phantomjs to see how they compare. I just delegated to the wrong method. Sorry for this.
