### ISSUE TITLE
getOuterHtml returns itself?

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#34]
I have this HTML snipper `<div id="with-inner"><span id="inner"></span></div>`. When querying "inner" and calling `getOuterHtml` the method returns `<span id="inner"></span>` which should not be the case, right? What is expected here? Maybe `<span id="inner"></span>`? I'm not sure about it...

**Comment by ui4j** [comment]
HTML & Javascript test

```html
<div id="with-inner"><span id="inner"></span></div>
```

```javascript
alert(document.querySelector('#inner').outerHTML);
```

JSFiddle [test](https://jsfiddle.net/6npuu86y/)

--

Here is Ui4j test:

```java
package com.ui4j.test;

import com.ui4j.api.browser.BrowserEngine;
import com.ui4j.api.browser.BrowserFactory;
import com.ui4j.api.browser.Page;
import com.ui4j.api.dom.Element;

public class Main {

	public static void main(String[] args) {
		BrowserEngine webkit = BrowserFactory.getWebKit();
		Page page = webkit.navigate("about:blank");
		page.show();
		page.getDocument().getBody().setInnerHTML("<div id=\"with-inner\"><span id=\"inner\"></span></div>");
		System.out.println(page.getDocument().query("#inner").getOuterHTML());
	}
}
```

Both javascript and ui4j sample return same result which is `<span id="inner"></span>`

May be you should call getParent before getOuterHTML for your case. `page.getDocument().query("#inner").getParent().getOuterHTML()`

**Comment by hstaudacher** [comment]
maybe. Fine for me. It was just weird ;). But if it's this way I'm fine with it. Maybe some JavaDoc would help.

**Comment by ui4j** [comment]
Although ui4j-webkit requires Java 8, ui4j-api is compatible with Java 7. Because of this requirement i didnt use Optional feature. But, Its better to drop Java 7 compatibility and use Optional feature.

**Comment by hstaudacher** [comment]
Nice to hear ;). Thanks.
