### ISSUE TITLE
getSiblings not working

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#38]
I have the following html snippet:

```html
    <ul id="list">
      <li>a</li>
      <li class="b">b</li>
      <li>c</li>
    </ul>
```

when calling `getSiblings()` or `getSiblings( "li" )` on `query( ".b" )` it always returns an empty list. I think it should it contain the two `li` elements, right?

**Comment by hstaudacher** [comment]
Btw. the same is true for `getNextSibling`. I think there is something wrong with the sibling determination.

**Comment by ui4j** [comment]
Thanks for the bug report. Implementation of the `getSiblings` and `getSiblings(String)` is fixed.
