### ISSUE TITLE
Fix API inconsistencies

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#39]
I noticed that there are some API inconsistencies. This has something to do with the Java 8 Optional migration. The following methods should also return optional from my point of view:

* `Element.getOffsetParent`
* `Element.getNextSibling`
* `Element.getContentDocument` **<- not sure about this**
* `Element.getCss`
* `Element.getText`
* `Element.getValue`
* `Element.getTitle`
* `Element.getId` **<- does an element without this id attribute has an id?**
* `Element.getAttribute`
* `Element.getPosition` **<- does an element have a position if it's not attached?**
* `Document.getTitle`
* `Document.getElementFromPoint`
* `Option.getText` **<- does this method make sense at all? If yes types like Input need to have getValue as well but it's on the element. I tend to remove this method. Also valid for the setText method.**
* `Option.getValue` **<- same as with Option.getText**
* `Option.getInput`
* `Select.getSelection`
* `Window.getLocation` **<- does this exist for headless mode?**

Not sure if all make sense but I think most of them are optionals as well.

**Comment by ui4j** [comment]
> Element.getOffsetParent
> Element.getNextSibling
> Element.getContentDocument
> Element.getCss
> Element.getText
> Element.getValue
> Element.getTitle
> Element.getId
> Element.getAttribute
> Document.getTitle
> Document.getElementFromPoint
> Select.getSelection

Done

> Option.getText, Option.getText, Option.getValue, Option.setValue

I agree, these methods are unnecessary and removed

> Element.getPosition

I am not sure how to know if position exist or not. May be i should return Optional.empty if both left and top position is equal to 0, 0

> Window.getLocation

Yes, its exist for headless mode. This method returns current url of the page similar to window.location.href. May be i should rename the method to more understandable name.

**Comment by ui4j** [comment]
`Window.getLocation` never returns null so that its not needed to return Optional.

> Element.getPosition

Done, If the Element is not an instanceof HTMLElementImpl an Optional.empty is returned.
