### ISSUE TITLE
Element.getText returns present optional

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#40]
If an element has no text the current implementation returns an Optional with a value. This means the text is present but it isn't.

**Comment by ui4j** [comment]
Fixed. If `org.w3c.Element.getTextContent()` is empty string `WebKitElement.getText` returns `Optional.empty()`.

**Comment by ui4j** [comment]
Additionally `Element.getAttribute` `Element.getValue` `Element.getTitle` `Element.getId` `Element.getId` `Document.getTitle` methods returns Optional.empty if the return value is empty string.
