### ISSUE TITLE
Request and Response headers differ

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#48]
Is it by purpose that the two `getHeaders` method signatures differ ?

From `Request`:
```java
public Map<String, String> getHeaders()
```
From `Response`:
```java
public Map<String, List<String>> getHeaders();
```

**Comment by ui4j** [comment]
`URLConnection.setRequestProperty(String, String)` accepts key value but `URLConnection.getHeaderFields()` returns `Map<String,List<String>>` and `URLConnection.getHeaderField` returns only the last value.

May be i should change the Request.headers to `Map<String, List<String>>` to support [multiple header values] (http://stackoverflow.com/questions/3096888/standard-for-adding-multiple-values-of-a-single-http-header-to-a-request-or-resp).

**Comment by ui4j** [comment]
Fixed, both `Request` and `Response` has symmetric header value now.
