### ISSUE TITLE
DialogHandlers are misplaced

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#51]
Currently AlertHandler and co are added to the Page while Interceptor is added to the PageConfiguration. Adding the Interceptor to the config makes sense because you may want to intercept the first request.

But what about navigating to a page that opens an alert before the document is ready? This call is blocking. So, would it make sense to move the adding of Dialog handlers also to the PageConfiguration to allow adding them before the page is loaded?

**Comment by ui4j** [comment]
Thanks for the suggestion. `AlertHandler` moved to `PageConfiguration`.

**Comment by hstaudacher** [comment]
Ok thanks. But what about `ConfirmHandler` and `PromptHandler`?

**Comment by ui4j** [comment]
Yes, its my mistake. `ConfirmHandler` and `PromptHandler` move to `PageConfiguration`.
