### ISSUE TITLE
Weird relative path resolvment

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#54]
I have the following html file called `ReadTest.html` hosted on an http server (NO file url):

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Fancy Title</title>
  </head>
  <body>
    <img id="image" src="resources/test.png" />
  </body>
</html>
```

When accessing it from a real browser the server gets these requests:
```
/ReadTest.html
/resources/test.png
```

When accessing it from UI4J it gets these requests:
```
/ReadTest.html
/ReadTest.html/http://127.0.0.1:58844/resources/test.png
```

Why is the relative resource path resolved so weird?

**Comment by ui4j** [comment]
Thanks for the bug report. Its fixed.
