### ISSUE TITLE
browser object is null on ubuntu server 14.10

### ISSUE THREAD

**Issue by rc183** [ui4j/ui4j#56]
Hi,

I try to use ui4j but when I launch my jar on ubuntu server 14.10, my browser object is null with the code : BrowserEngine browser = BrowserFactory.getBrowser(BrowserType.WebKit);

Any idea why ?

Thanks

**Comment by ui4j** [comment]
Ui4j requires ui4j-all or ui4j-webkit jar. Most probably your classpath contains only ui4j-api.jar.

**Comment by rc183** [comment]
In fact I realize that I'm not able to compile the ui4j maven project.

I have always the error : Failed to execute goal on project ui4j-webkit: Could not resolve dependencies for project com.ui4j:ui4j-webkit:bundle:2.0.0-SNAPSHOT: Could not find artifact com.ui4j:ui4j-api:jar:2.0.0-SNAPSHOT

How can I compile the last source code of ui4j with maven ?

Thank you.

**Comment by rc183** [comment]
Ok it was an error in my maven version.

Now I can execute my jar in command line but another error : Xlib:  extension "RANDR" missing on display ":99.0".

Any idea why ?

Thanks

**Comment by ui4j** [comment]
libxslt is required by the JavaFX webkit implementation. Could you please check if libxslt is installed. If its not try to install it with this command `sudo apt-get install libxslt1-dev`.

**Comment by rc183** [comment]
Ok Thank you. 

I have always the error Xlib: extension "RANDR" missing on display ":99.0". but it works.
