### ISSUE TITLE
How do I wait for JavaScript to finish executing?

### ISSUE THREAD

**Issue by JoeJErnst** [ui4j/ui4j#59]
I am simulating user interaction with a web page and I need to know how to either register a callback or wait for JavaScript to finish, preferably without using Thread.sleep().

For example, I am using `myDocument.query(SUBMIT_BUTTON).get().click()` to simulate submitting a form, which makes an Ajax call and then updates the DOM with the results.  My Java code needs to wait for that Ajax call to finish and the DOM to be updated before it can use the next call to `myDocument.query()`.  The same goes for the inital page load; I need to wait for the onLoad() javascript to finish before querying the DOM. 

How do I accomplish this?  Thank you in advance...

**Comment by ui4j** [comment]
> I need to wait for the onLoad() javascript to finish before querying the DOM.

Ui4j automatically waits pageLoad event. Its not required to use sleep or etc to wait the pageLoad event. Check [this](https://github.com/ui4j/ui4j/blob/master/ui4j-sample/src/main/java/com/ui4j/sample/CnnTechNews.java) example for sample usage. After the click [event](https://github.com/ui4j/ui4j/blob/master/ui4j-sample/src/main/java/com/ui4j/sample/CnnTechNews.java#L23) Ui4j waits until the pageLoad event.

**Comment by ui4j** [comment]
> My Java code needs to wait for that Ajax call to finish and the DOM to be updated before...

I just add add new [sample code](https://github.com/ui4j/ui4j/blob/master/ui4j-sample/src/main/java/com/ui4j/sample/FormPost.java) snippet to show listen DOM modifications. Let me know if this sample usage is enough to simulate your use case to wait DOM modifications without using `Thread.sleep(long)`.

**Comment by JoeJErnst** [comment]
I tried using the DOMSubtreeModified event like you put in your sample code, but that fires on *every* DOM modification, right?  I somehow need to know when the DOM is done being modified, then I can continue my code execution.  The Javascript in the page will perform an unknown number of modifications.

**Comment by sizwethekingrat** [comment]
@JoeJErnst  Agreed. I'm assessing this library for my company and if I cannot know when angular is done doing it's magic it's a deal-breaker...

@ui4j please give us a graceful solution as I see that your underlying webEngine has a stateProperty listener but when I use it it complains that the thread is not an FX Application Thread.
```java
Page page = browser.navigate("http://localhost:8084/whatever");

WebEngine engine = (WebEngine) page.getEngine();

engine.getLoadWorker().stateProperty().addListener((observable, oldValue, newValue) -> {
            System.out.println(observable);
            System.out.println(oldValue);
            System.out.println(newValue);
        });
```
gives me
>java.lang.IllegalStateException: Not on FX application thread; currentThread = main
>	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:204)
>	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:438)
>	at javafx.scene.web.WebEngine.checkThread(WebEngine.java:1182)
>	at javafx.scene.web.WebEngine$LoadWorker.stateProperty(WebEngine.java:1223)

**Comment by ui4j** [comment]
Hi,

> I use it it complains that the thread is not an FX Application Thread.

You must execute all JavaFx methods from JavaFx Thread.
Please execute your sample code with javafx.application.Platform.runLater()

```java
javafx.application.Platform.runLater(() -> {
engine.getLoadWorker().stateProperty().addListener((observable, oldValue, newValue) -> {
            System.out.println(observable);
            System.out.println(oldValue);
            System.out.println(newValue);
        });
});
```
