### ISSUE TITLE
Reliably and easily submit a form?

### ISSUE THREAD

**Issue by flyrev** [ui4j/ui4j#60]
The Form class does not have a submit().

Why not?

**Comment by ui4j** [comment]
Thanks for the suggestion. New `Form.submit()` method could be used to submit html forms. I am going to release this feature with version 2.1.0. You could checkout and build ui4j from master branch to use submit method.

**Comment by ui4j** [comment]
Hi, version 2.1.0 is released and published to maven central repository.

**Comment by grayskripko** [comment]
thx
