### ISSUE TITLE
Make requests through a socks proxy

### ISSUE THREAD

**Issue by nianevitch** [ui4j/ui4j#80]
How to make requests through a socks proxy? I need to be able to support SOCKS and http (in the future). Thanks!

**Comment by ui4j** [comment]
Hi,

Did you try to use `socksProxyHost` and `socksProxyPort` system property.

--

[2.4 Java Networking and Proxies](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)
```
There are 2 system properties related to SOCKS:
socksProxyHost for the host name of the SOCKS proxy server
socksProxyPort for the port number, the default value being 1080
```

**Comment by nianevitch** [comment]
thanks! solved it through:

```
		System.setProperty("socksProxyHost", "127.0.0.1");
		System.setProperty("socksProxyPort", "4568");
```

**Comment by juanla** [comment]
Hello. There are a way to use a Proxy in more precise level?

I want go across a proxy when I connect a web without change system network config.
