### ISSUE TITLE
NullPointerException when navigate to empty page (about:blank)

### ISSUE THREAD

**Issue by Ocean15** [ui4j/ui4j#97]
I think there is a !=null check in the WebViewCreator missing in line 307 for the latch.

Best regards
Ocean15

**Comment by ui4j** [comment]
Thanks for the bug report.
I fixed the NullPointerException.

Here is the pom configuration to update your ui4j version.
Version 2.2.x use jitpack repo instead of Maven central.

```xml
<repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
</repository>

<dependency>
    <groupId>com.github.ui4j.ui4j</groupId>
    <artifactId>ui4j-all</artifactId>
    <version>2.2.2</version>
</dependency>
```
